extends: airbnb-base
parser: typescript-eslint-parser
plugins:
  - typescript
settings:
  import/resolver:
    node:
      extensions:
        - .ts
  import/parsers:
    typescript-eslint-parser: [.ts]
rules:
  no-undef: off
  space-infix-ops: off
  import/extensions: [error, ignorePackages, {
    js: never,
  }]
  typescript/no-unused-vars: error
overrides:
  - files: '**/*.test.ts'
    rules:
      import/no-extraneous-dependencies: off
