extends: airbnb-base
parser: typescript-eslint-parser
settings:
  import/resolver:
    node:
      extensions:
        - .ts
  import/parsers:
    typescript-eslint-parser: [.ts]
rules:
  no-undef: off
  import/extensions: [error, ignorePackages, {
    js: never,
  }]
